sonata_classification:

    class:
        tag:          Application\Sonata\ClassificationBundle\Entity\Tag
        category:     Application\Sonata\ClassificationBundle\Entity\Category
        collection:   Application\Sonata\ClassificationBundle\Entity\Collection

    #admin:
    #    tag:
    #        class:        Sonata\ClassificationBundle\Admin\TagAdmin
    #        controller:   SonataAdminBundle:CRUD
    #        translation:  SonataClassificationBundle
    #    category:
    #        class:        Sonata\ClassificationBundle\Admin\CategoryAdmin
    #        controller:   SonataAdminBundle:CRUD
    #        translation:  SonataClassificationBundle
    #    collection:
    #        class:        Sonata\ClassificationBundle\Admin\CollectionAdmin
    #        controller:   SonataAdminBundle:CRUD
    #        translation:  SonataClassificationBundle

doctrine:

    orm:
        entity_managers:
            default:
                #metadata_cache_driver: apc
                #query_cache_driver: apc
                #result_cache_driver: apc
                mappings:
                    ApplicationSonataClassificationBundle: ~
                    #SonataClassificationBundle: ~
