<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser {

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var string
     */
    protected $bakeFrequency;

    /**
     * @var string
     */
    protected $sex;

    /**
     * @var array
     */
    protected $bakeChoises;

    /**
     * @var string
     */
    protected $children;

    /**
     * @var string
     */
    protected $age;

    /**
     * @var string
     */
    protected $campaign;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId() {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getBakeFrequency() {
        return $this->bakeFrequency;
    }

    /**
     * Set bakeFrequency
     *
     * @param string $bakeFrequency
     * @return bakeFrequency
     */
    public function setBakeFrequency($bakeFrequency) {
        $this->bakeFrequency = $bakeFrequency;
        return $this;
    }

    /**
     * @return string
     */
    public function getSex() {
        return $this->sex;
    }

    /**
     * Set sex
     *
     * @param string $sex
     * @return sex
     */
    public function setSex($sex) {
        $this->sex = $sex;
        return $this;
    }

    /**
     * @return string
     */
    public function getCampaign() {
        return $this->campaign;
    }

    /**
     * Set campaign
     *
     * @param string $campaign
     * @return campaign
     */
    public function setCampaign($campaign) {
        $this->campaign = $campaign;
        return $this;
    }

    /**
     * @return string
     */
    public function getBakeChoises() {
        return $this->bakeChoises;
    }

    /**
     * Set bakeChoises
     *
     * @param string $bakeChoises
     * @return bakeChoises
     */
    public function setBakeChoises($bakeChoises) {
        $this->bakeChoises = $bakeChoises;
        return $this;
    }

    /**
     * Set children
     *
     * @param string $children
     * @return children
     */
    public function setChildren($children) {
        $this->children = $children;
        return $this;
    }

    /**
     * @return string
     */
    public function getChildren() {
        return $this->children;
    }

    /**
     * Set age
     *
     * @param string $age
     * @return age
     */
    public function setAge($age) {
        $this->age = $age;
        return $this;
    }

    /**
     * @return string
     */
    public function getAge() {
        return $this->age;
    }

    public function setEmail($email) {
        $this->email = $email;
        if ($this->getUsername() == null) {
            $this->username = $email;
            $this->password = $email;
            $this->plainPassword = $email;
        }
    }

    public function setEmailCanonical($emailCanonical) {
        $this->emailCanonical = $emailCanonical;
        if ($this->getUsernameCanonical() == null) {
            $this->usernameCanonical = $emailCanonical;
        }
    }

    /**
     * @return string
     */
    public function getFullname() {
        return sprintf("%s %s", $this->getEmail());
    }

    /**
     * Returns a string representation
     *
     * @return string
     */
    public function __toString() {
        return $this->getUsername() ? : '-';
    }

}